[build]
  publish = "public"
  command = "hugo --minify"

  [build.environment]
  HUGO_VERSION = "0.147.8"
  HUGO_ENV = "production"
  GO_VERSION = "1.21"
  GONOSUMCHECK = "*"
  GONOSUMDB = "*"
  GOFLAGS = "-mod=mod"
  GOPATH = "/opt/build/cache/go"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
